### PR TITLE
IBX-4359: Added AuthorizationHeaderRESTRequestMatcher for REST

### PR DESCRIPTION
**Pull request by Steveb-p**
* https://github.com/ibexa/rest/pull/39

### CODE REVIEW

**Comment by Steveb-p** [comment]
@webhdx, @glye  - @bdunogier would like JWT to be enabled by default in new installations. What is our take on this?

**Comment by glye** [comment]
@Steveb-p Can you give us a desc of the concerns? I'll have a look in ca half an hour.

**Comment by glye** [comment]
@Steveb-p I don't know this well enough, correct me if I'm wrong. We support 5 auth schemes for the rest api, jwt is one of them. Only one can be be used at a time until now, and session-based is the default. These PRs are to have both session and jwt enabled at the same time. That means no BC problem, since session-based will still work as it did before, right?

And it implies a hierarchy - if both are present, jwt is used and session is ignored.

Not sure about security implications. There could be some confusion. Let's say session is used first and then jwt with a different account. Then you could say that two different auths are present at the same time for the same client instance. But if session is ignored, that should not matter, as long as all aspects of the system agree on this, and we don't have some component we forgot about still using the session-based auth while the rest uses jwt. But if we're only talking about rest api, then there are no other components present for this auth, and we're good. Or if GraphQL is included in this, it's 2.

**Comment by Steveb-p** [comment]
@glye These PR's do indeed make it so you can authenticate in multiple different ways against REST endpoints. Specifically for our current case, both JWT and session (or more accurately, cookie) based authentications are available.

Session-based authentication will work exactly as before - unless `Authorization` header is used. That is `Authorization` header authentication takes precedence over the cookie. The main argument for this order is that session-based authentication has a side effect: all requests need to be processed in order. Session need to be closed before next request is processed. This makes it so that long-running POST operations might block any further GET requests, until they are done.

Multiple authorization methods will never occur. That's a built-in Symfony feature. We are using firewalls to differentiate between token, stateless authentication and session, cookie based one. Then if we need more authentication methods (other than JWT) we could use firewalls (as we do currently) or introduce more authorization guards under the same firewall (I think a different, but functionaly equivalent system is available since Symfony 5.2).
So once a specific authorization type is picked (for example, `Authorization` header is present), then all other types are disabled in context of this request.

**Review by adamwojs — APPROVED** [review]

**Comment by bdunogier** [comment]
Is anything blocking this ? It seems to me that everybody agrees.

**Review by webhdx — APPROVED** [review]

**Comment by Steveb-p** [comment]
> Is anything blocking this ? It seems to me that everybody agrees.

The original PR remains in QA queue, which prevents this one from being merged.

**Comment by micszo** [comment]
@bdunogier It should be tested by tomorrow, if that's ok.

**Review by mnocon — APPROVED** [review]

**Comment by bdunogier** [comment]
Actually @glye it would be ideal if GraphQL was also concerned here, as Sessions/Cookies aren’t really supported by many GraphQL clients...

**Comment by glye** [comment]
"Potential for improvement", then... :)

**Pull request merged**
